services:
  mockoon:
    image: mockoon/cli:latest
    container_name: mockoon-auth
    ports:
      - "3000:3000"
    volumes:
      - ./mock/authorizing.json:/data:ro
    command: ["--data", "data", "--port", "3000"]
